# Generated by Django 3.2.5 on 2021-08-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downflow',
            old_name='down_flow',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='downflow',
            old_name='down_flow_confirm',
            new_name='flow_confirm',
        ),
        migrations.RenameField(
            model_name='downflow',
            old_name='down_flow_trade',
            new_name='flow_trade',
        ),
        migrations.RenameField(
            model_name='upflow',
            old_name='up_flow',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='upflow',
            old_name='up_flow_confirm',
            new_name='flow_confirm',
        ),
        migrations.RenameField(
            model_name='upflow',
            old_name='up_flow_trade',
            new_name='flow_trade',
        ),
    ]
