# Generated by Django 3.2.5 on 2021-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('xbt_usd', models.FloatField(verbose_name='XBTUSD')),
                ('xbt_u21', models.FloatField(verbose_name='XBTU21')),
            ],
        ),
    ]
