# Generated by Django 3.2.5 on 2021-10-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_u21hourdata_u21minutedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimedata',
            name='xbt_u21',
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='ask_sub',
            field=models.FloatField(default=0, verbose_name='ASKSUB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='ask_usd',
            field=models.FloatField(default=0, verbose_name='ASKUSD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='bid_sub',
            field=models.FloatField(default=0, verbose_name='BIDSUB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='bid_usd',
            field=models.FloatField(default=0, verbose_name='BIDUSD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='xbt_sub',
            field=models.FloatField(default=0, verbose_name='XBTSUB'),
            preserve_default=False,
        ),
    ]
