# Generated by Django 3.2.5 on 2021-11-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20211122_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutedata',
            name='real',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='minutesubdata',
            name='real',
            field=models.CharField(default='', max_length=4),
        ),
    ]
