# Generated by Django 3.2.5 on 2021-08-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BooleanField(default=False)),
                ('buy_order_time', models.DateTimeField(blank=True, null=True)),
                ('buy_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(default=100)),
                ('buy_price', models.FloatField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('sell_order_time', models.DateTimeField(blank=True, null=True)),
                ('sell_time', models.DateTimeField(blank=True, null=True)),
                ('sell_price', models.FloatField(default=0)),
                ('max_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earning_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TradeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_trade', models.BooleanField(default=True)),
                ('real_trade', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('buy_rate_option', models.IntegerField(default=10)),
                ('sell_rate_option', models.IntegerField(default=10)),
            ],
        ),
    ]
