# Generated by Django 3.2.5 on 2021-08-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesult',
            name='signal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
